15 static file storage
codEnjoyer/BeatBox-Booking-Backend pull request #21
Opened 2024-05-14 04:44 UTC by 2piCode

2024-05-14 15:01 UTC, codEnjoyer commented on setup.cfg
> +max-line-length = 80
договаривались о длине строки в 100 символов

2024-05-14 15:01 UTC, codEnjoyer commented on setup.cfg
> +line_length = 80
100 символов

2024-05-14 15:04 UTC, codEnjoyer commented on src/api/file.py
> +        name=file[0].name, extension=file[0].extension, url=file[1].url
Почему к файлу можно обратиться по индексу и при создании их возвращается два? 😮

2024-05-14 15:05 UTC, codEnjoyer commented on src/domain/models/repositories/file_bucket.py
> +class FileBucketRepository:
от абстрактного не наследуешься?

2024-05-14 15:06 UTC, codEnjoyer commented on src/domain/models/repositories/file_bucket.py
> +        self.valid_image_types = (image.Jpeg, image.Png, image.Webp)
стоит валидные изображения как-то связать с перечислением, которое в БД держим

2024-05-14 15:07 UTC, codEnjoyer commented on src/domain/models/repositories/file_bucket.py
> +    async def create(self, upload_file: UploadFile, key: str) -> FileBucketRead:
предлагаю переименовать на upload

2024-05-14 15:11 UTC, codEnjoyer requested changes
верни форматирование обратно 😭

2024-05-14 16:43 UTC, 2piCode commented on src/domain/models/repositories/file_bucket.py
> +class FileBucketRepository:
Нет, ничего из абстрактного репозитория не используется, а только усложняет работу

2024-05-14 16:47 UTC, 2piCode commented on src/api/file.py
> +        name=file[0].name, extension=file[0].extension, url=file[1].url
Первый файл - модель из базы данных со всеми полями, чтобы ее не изменять решил возвращать tuple второй элемент которого - файл из object storage

2024-05-14 16:53 UTC, codEnjoyer commented on src/api/file.py
> +        name=file[0].name, extension=file[0].extension, url=file[1].url
мне кажется, стоит тогда написать что-то вроде
```python
orm_file, bucket_file = await file_service.create(file)
```

2024-05-14 16:55 UTC, codEnjoyer commented on src/domain/models/repositories/file_bucket.py
> +class FileBucketRepository:
главное, чтоб в будущем проблем с переиспользованием не возникло

2024-05-15 14:31 UTC, codEnjoyer approved these changes

2024-05-15 14:39 UTC, merged