Добавлены основные модели данных и инфраструктура для работы БД (#3)
codEnjoyer/BeatBox-Booking-Backend pull request #5
Opened 2024-03-26 18:35 UTC by dolbikcop

🤡

2024-03-27 17:02 UTC, codEnjoyer commented on pyproject.toml
> +httpx = "^0.27.0"
Убрать зависимость

2024-03-27 17:02 UTC, codEnjoyer commented on src/config.py
> +    def database_url(self) -> PostgresDsn:
Отдавать строку

2024-03-27 17:02 UTC, codEnjoyer commented on src/config.py
> +from pydantic import PostgresDsn
Переименовать файл в settings.py

2024-03-27 17:02 UTC, codEnjoyer commented on migrations/env.py
> +from src.models import *
добавить # noqa

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/review.py
> +    author: Mapped["User"] = relationship(back_populates="reviews", lazy='joined')
добавить внешние ключи

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/review.py
> +    date: Mapped[str] = mapped_column(DateTime, default=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
поменять на func.now

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/review.py
> +    grade: Mapped[int] = mapped_column(Integer(), CheckConstraint('grade > 0 AND grade <= 5'))
убрать ()

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/slot.py
> +    studio: Mapped["Studio"] = relationship(back_populates="slots", lazy="joined")
добавить комнату и поменять relationship

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/slot.py
> +    is_free: Mapped[bool] = mapped_column(Boolean, default=True)
слоты только для забронированных, убрать is_free

2024-03-27 17:02 UTC, codEnjoyer commented on src/models/slot.py
> +    tenant: Mapped["User"] = relationship(back_populates="reserved_slots")
поменять на booked_by

2024-03-27 17:02 UTC, codEnjoyer commented on tests/api/test_startup.py
> +    assert response.status_code == 404
используй HTTPStatus.NOT_FOUND

2024-04-03 13:31 UTC, dolbikcop commented on pyproject.toml
> +httpx = "^0.27.0"
httpx нужен для тестов

2024-04-03 16:16 UTC, codEnjoyer commented on src/models/room.py
> +    slots: Mapped[list["Slot"]] = relationship(back_populates="room")
добавь каскадное удаление

2024-04-03 16:19 UTC, codEnjoyer commented on src/models/studio.py
> +    rooms: Mapped[list["Room"]] = relationship(back_populates="studio")
добавь каскадное удаление

2024-04-03 16:20 UTC, codEnjoyer commented on src/models/user.py
> +    email: Mapped[str] = mapped_column(String(100), unique=True, index=True)
не вижу смысла в индексе на почте

2024-04-03 16:20 UTC, codEnjoyer commented on src/models/user.py
> +    hashed_password: Mapped[str] = mapped_column(String(200))
боюсь, что ограничение длины хеша пароля может выйти боком. хотя бы до 1024 увеличить

2024-04-03 16:21 UTC, codEnjoyer commented on src/settings.py
> +        ).__str__()
лучше оберни в str(), привычнее будет выглядеть. напрямую __**__ методы не принято дергать

2024-04-03 16:24 UTC, codEnjoyer requested changes

2024-04-03 16:24 UTC, codEnjoyer commented on startup.py
> +    uvicorn.run("src.main:app",
мне кажется, лучше использовать объекты из uvicorn'а, вроде Config и Server

2024-04-23 06:56 UTC, codEnjoyer approved these changes

2024-04-24 16:10 UTC, merged